{{- $namespace := .Release.namespace }}
{{- if .Values.global.debug }}
apiVersion: v1
kind: Pod
metadata:
  name: debug-env
  namespace: {{ $namespace }}
  labels:
    aadpodidbinding: osdu-identity
spec:
  volumes:
    - name: azure-keyvault
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-keyvault

  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumeMounts:
        - name: azure-keyvault
          mountPath: "/mnt/azure-keyvault"
          readOnly: true
      env:

        # Static Variables
        - name: server.servlet.contextPath
          value: /

        - name: server_port
          value: "80"

        - name: azure_activedirectory_session_stateless
          value: "true"

        - name: cosmosdb_database
          value: osdu-db

        - name: service_domain_name
          value: contoso.com

        # Secret Variables Active Directory
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: tenantid
        - name: aad_client_id
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: application-appid
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientid
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientpassword
        - name: appinsights_key
          valueFrom:
            secretKeyRef:
              name: central-logging
              key: appinsights

        # Config Map Variables
        - name: KEYVAULT_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: ENV_KEYVAULT
        - name: REDIS_DB_PARTITION
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: REDIS_DB_PARTITION
{{- end }}
