
{{- $namespace := .Release.namespace }}
{{- $serviceType := .Values.service.type }}
{{- $servicePort := .Values.service.port }}
{{- $release := .Release.Name }}
{{- range .Values.serverless }}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .function }}
  namespace: {{ $namespace }}
  labels:
    deploymentName: {{ .function }}
spec:
  scaleTargetRef:
    deploymentName: {{ .function }}
  triggers:
  - type: azure-servicebus
    metadata:
      type: serviceBusTrigger
      direction: in
      name: message
      subscriptionName: {{ .servicebusSubscription }}
      topicName: {{ .servicebusTopic }}
      connection: SERVICE_BUS

---
{{- end }}
