{{- $namespace := .Release.namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap }}
  namespace: {{ $namespace }}
data:
  DES_SERVICE_HOST: https://{{ .Values.ingress.dns }}
  REDIS_INSTANCE_PORT: "6380"
  APP_ENVIRONMENT_IDENTIFIER: cloud
  CLOUDPROVIDER: azure
  PORT: "80"
  SIDECAR_URL: "{{ .Values.configEnv.sidecarUrl}}"
  SIDECAR_ENABLE_INSERT: "{{ .Values.configEnv.sidecarEnableInsert}}"
  SIDECAR_ENABLE_GET: "{{ .Values.configEnv.sidecarEnableGet}}"
  SIDECAR_ENABLE_DELETE: "{{ .Values.configEnv.sidecarEnableDelete}}"
  SIDECAR_ENABLE_QUERY: "{{ .Values.configEnv.sidecarEnableQuery}}"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: osdu-svc-config
  namespace: {{ $namespace }}
data:
  ENV_KEYVAULT: https://{{ .Values.azure.keyvault }}.vault.azure.net/
  REDIS_DB_AIRFLOW: "1"
  REDIS_DB_PARTITION: "2"
  REDIS_DB_ENTITLEMENTS: "3"
  REDIS_DB_LEGAL: "4"
  REDIS_DB_STORAGE: "5"
  REDIS_DB_INDEXER: "6"
  REDIS_DB_SEARCH: "7"
  REDIS_DB_DELIVERY: "8"
  REDIS_DB_FILE: "9"
  REDIS_DB_SDMS: "10"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seistore-svc-sidecar-properties
  namespace: {{ $namespace }}
data:
  ASPNETCORE_URLS: "{{ .Values.configEnv.sidecarUrls }}"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/aspnetapp.pfx"
  ASPNETCORE_ENVIRONMENT: {{ .Values.configEnv.sidecarEnvironment }}
