{{- $namespace := .Release.namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap }}
  namespace: {{ $namespace }}
data:
  DES_SERVICE_HOST: https://{{ .Values.ingress.dns }}
  REDIS_INSTANCE_PORT: "6380"
  APP_ENVIRONMENT_IDENTIFIER: cloud
  CLOUDPROVIDER: azure
  PORT: "80"
