#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

{{- if .Values.azure.keyvault.secrets -}}
{{- $name := include "standard-ddms.name" . }}
{{- $labels := include "standard-ddms.common-labels" . }}
{{- $namespace := .Release.Namespace -}}
{{- $azTenant := .Values.azure.tenant -}}
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ $name }}-secret
  namespace: {{ $namespace }}
  labels: {{ $labels | nindent 4 }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ $name }}-secret
    type: Opaque
    data:
  {{- range .Values.azure.keyvault.secrets }}
    - objectName: {{ .obj | quote }}
      key: {{ .key | quote }}
  {{- end }}
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    tenantId: "{{ .Values.azure.tenant }}"
    subscriptionId: "{{ .Values.azure.subscription }}"
    resourceGroup: "{{ .Values.azure.resourcegroup }}"
    keyvaultName: "{{ .Values.azure.keyvault.name }}"
    objects: |
      array:
        {{- range .Values.azure.keyvault.secrets }}
        - |
          objectName: {{ .obj }}
          objectType: secret
        {{- end }}
{{- end -}}
