{{- $namespace := .Release.Namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "schema-data-initialization-job"
  namespace: {{ $namespace }}
  labels:
    app: "schema-data-initialization-job"
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        aadpodidbinding: osdu-identity
    spec:
      restartPolicy: OnFailure
      containers:
      - image: {{ .Values.image.repository }}/schema-data-init:{{ .Values.image.tag | default .Chart.Version }}
        imagePullPolicy: Always
        name: "schema-data-init"
        env:
        - name: AZURE_DNS_NAME
          value: {{ .Values.ingress.dns }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.azure.tenant_id }}
        - name: AZURE_AD_APP_RESOURCE_ID
          value: {{ .Values.azure.resource_id }}
        - name: AZURE_CLIENT_ID
          value: {{ .Values.azure.client_id }}
        - name: AZURE_CLIENT_SECRET
          value: {{ .Values.azure.client_secret }}