{{ if .Values.appinsightstatsd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: appinsights-statsd
spec:
  type: ClusterIP
  ports:
  - port: 8125
    protocol: UDP
  selector:
    app: appinsights-statsd
{{ end }}