#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  Rate limit document for reference : https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/
{{- $namespace := .Release.Namespace }}
{{- $release := .Release.Name }}
{{- $ratelimitenabled := .Values.global.resiliency.rateLimit.enabled | default false }}
{{- $max_tokens := .Values.global.resiliency.rateLimit.max_tokens | default 0 }}
{{- $tokens_per_fill := .Values.global.resiliency.rateLimit.tokens_per_fill | default 0 }}
{{- $fill_interval := .Values.global.resiliency.rateLimit.fill_interval | default 0 }}
{{ if $ratelimitenabled }}
{{- range .Values.configuration }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .service }}-ratelimit
  namespace: {{ $namespace }}
spec:
  workloadSelector:
    labels:
      app: {{ .service }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND   # will match outbound listeners in all sidecars
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: {{ $max_tokens }}    #The maximum tokens that the bucket can hold. 
                tokens_per_fill: {{ $tokens_per_fill }}  #The number of tokens added to the bucket during each fill interval.    
                fill_interval: {{ $fill_interval }}   #The fill interval that tokens are added to the bucket in seconds.
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: true
                  header:
                    key: x-local-rate-limit
                    value: 'true'
{{ end }}
---
{{ end }}