{{- $namespace := .Release.Namespace }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "osdu-probe-cronjob"
  namespace: {{ $namespace }}
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}
            aadpodidbinding: osdu-identity
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: azure-keyvault
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: azure-keyvault
          containers:
          - image: {{ .Values.image.repository }}/azure-probe-test-client:{{ .Values.image.tag | default .Chart.AppVersion }}
            imagePullPolicy: Always
            name: "osdu-probe-cron"
            volumeMounts:
            - name: azure-keyvault
              mountPath: "/mnt/azure-keyvault"
              readOnly: true
            env:
            - name: OSDU_HOST
              value: {{ .Values.azure.dns }}
            - name: DATA_PARTITION
              value: {{ .Values.azure.partition }}
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: active-directory
                  key: tenantid
            - name: PRINCIPAL_ID
              valueFrom:
                secretKeyRef:
                  name: active-directory
                  key: principal-clientid
            - name: PRINCIPAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: active-directory
                  key: principal-clientpassword
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: active-directory
                  key: application-appid
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: central-logging
                  key: appinsights
            - name: VERSION
              value: {{ .Chart.Version }}