{{- $namespace := .Release.Namespace }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: {{ $namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: active-directory
    type: Opaque
    data:
    - objectName: "app-dev-sp-tenant-id"
      key: tenantid
    - objectName: "aad-client-id"
      key: application-appid
    - objectName: "app-dev-sp-username"
      key: principal-clientid
    - objectName: "app-dev-sp-password"
      key: principal-clientpassword
    - objectName: "app-dev-sp-id"
      key: principal-objectid
  - secretName: central-logging
    type: Opaque
    data:
    - objectName: "appinsights-key"
      key: appinsights
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    resourceGroup: "{{ .Values.azure.resourcegroup }}"
    keyvaultName: "{{ .Values.azure.keyvault }}"
    subscriptionId: "{{ .Values.azure.subscription }}"
    tenantId: "{{ .Values.azure.tenant }}"
    objects: |
      array:
        - |
          objectName: app-dev-sp-tenant-id
          objectType: secret
        - |
          objectName: aad-client-id
          objectType: secret
        - |
          objectName: appinsights-key
          objectType: secret
        - |
          objectName: app-dev-sp-username
          objectType: secret
        - |
          objectName: app-dev-sp-password
          objectType: secret
        - |
          objectName: app-dev-sp-id
          objectType: secret
