{{- define "osdu-helm-library.authpolicy" -}}
{{- $namespace := .Release.Namespace }}
{{- $release := .Release.Name }}
{{- $corsenabled := .Values.global.azure.corsEnabled | default false }}
{{- range .Values.configuration }}
{{- if .auth }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .service }}-jwt-authz
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .service }}
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
      to:
        - operation:
            notPaths: [
              {{- range .auth.disable }}
              {{ . | quote }},
              {{- end }}
            ]
            {{- if $corsenabled }}
            notMethods: ["OPTIONS"]
            {{- end }}
{{- end }}
---
{{- end }}
{{- end }}