# FIXME: PDSv1 specific properties
pds:
  datapartitions: <azure_bus_name>
  servicebus: <dataPartition_names>

# FIXME: Specific to OSDU deployment
azure:
  keyvault:
    secrets:
    - key: appinsight.key
      obj: appinsights-key

# FIXME: Specific to OSDU deployment
ingress:
  appGateway:
    issuer: letsencrypt-prod-dns
    enableKeyvaultCert: true

# TODO: Remove
deployment:
  replicaCount: 1

uri-pattern-filter:
  service: pds-backend
  uriPatterns:
  - "/petrel-ds/api/v1/hello"
  - "/petrel-ds/api/v1/healthz/details"
  - "/petrel-ds/api/v1/healthz"
  - "/petrel-ds/api/v1/version"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/download/batch"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/favorites"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/autosync"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/status"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/status/archive"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/status/restore"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/fetch"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/branches"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/branches/{branch}"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/screenshot"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/content"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/content/{storageId}/{fileName}"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/content/{storageId}/{fileName}/dowwnload"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/deeplink"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/screenshot"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/rawmodel/{entityId}"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/rawmodel"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/latest"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/content"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/content/raw"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/views"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/views/model"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/views/windowImage"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/views/raw"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/views/history"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/views/rawmodel"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/views/file"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/attachedDocuments/{documentKey}"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/entities/{entityId}/descendants"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/fetch"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}"
  - "/petrel-ds/api/v1/tenants/{tenantid}/projects/{projectid}/revisions/{revisionId}/changes"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/fetch"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/download"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/batch"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/bulk"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/large/{dataItemId}/upload"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/large/{dataItemId}/upload/multipart"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/large/{dataItemId}/upload/multipart/{uploadId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/large/{dataItemId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/large"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/dataItems/{dataItemId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/transfers/{transferId}/status"
  - "/petrel-ds/api/v1/tenants/{tenantId}/metrics/{metricType}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/features"
  - "/petrel-ds/api/v1/tenants/{tenantId}/features/users/{userId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/monitoring"
  - "/petrel-ds/api/v1/tenants/{tenantId}/reports/activity"
  - "/petrel-ds/api/v1/tenants/{tenantId}/legalTags/countries"
  - "/petrel-ds/api/v1/tenants/{tenantId}/legalTags"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/tags"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}/tags"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}/revisions/{revisionId}/tags"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/ingestion"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}/ingestion"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}/revisions/{revisionId}/ingest"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}/revisions/{revisionId}/ingest/selection"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}/revisions/{revisionId}/ingestionResult"
  - "/petrel-ds/api/v1/tenants/{tenantId}/fileindex"
  - "/petrel-ds/api/v1/tenants/{tenantId}/fileindex/{operationId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/testcontent/{contentId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}"
  - "/petrel-ds/api/v1/tenants/{tenantId}/projects/{projectId}/revisions/{revisionId}/projectInformation"
  - "/petrel-ds/api/v1/tenants/{tenantId}/settings"
  - "/petrel-ds/api/v1/tenants/{tenantId}/entitlement/groups"
  - "/petrel-ds/api/v1/tenants/{tenantId}/users/roles"
  - "/petrel-ds/api/v1/users/context"
  - "/petrel-ds/api/v1/users/partitions/{dataPartitionId}"
  - "/petrel-ds/api/v1/users/partitions"
  - "/petrel-ds/api/v1/plugins/extension/{releaseChannel}/{version}"
  - "/petrel-ds/api/v1/plugins/extension"
  - "/petrel-ds/api/v1/tenants/{tenantId}/status"
  - "/petrel-ds/api/v1/tenants/{tenantId}/configuration"

configuration:
  #######################
  # PDS Backend Service #
  #######################
  - service: pds-backend
    container:
      image: pds-backend
      tag: 1.4.347
      containerPort: 8080
    path: /petrel-ds/api/v1
    probe:
      readiness: 
        path: /petrel-ds/api/v1/healthz
      liveness: 
        path: /petrel-ds/api/v1/healthz
    auth:
      disable:
        - "/petrel-ds/api/v1/docs*"
        - "/petrel-ds/api/v1/healthz"
        - "/petrel-ds/api/v1/version"
        - "/petrel-ds/api/v1/hello"
    config:
      NODE_ENV: "production"
      ENVIRONMENT: "PROD"
      SVC_PORT: "8080"
      BASE_URI: "https://{{ .Values.ingress.dns }}"
      SERVICE_PATH: "/petrel-ds/api/v1"
      API_DOCUMENTATION_ENABLED: "1"
      LOG_SEVERITY: "debug"
      DEFAULT_USER_CONTEXT_DATA_PARTITION_ID: "{{ (split \",\" .Values.pds.datapartitions)._0 }}" 
      DEFAULT_USER_ASSOCIATION_DATA_PARTITION_ID: "{{ (split \",\" .Values.pds.datapartitions)._0 }}"
      SERVICE_BUS_NAMESPACE: "{{ .Values.pds.servicebus }}"
      FUNCTION_QUEUE_NAME: "petrel-storage-function"
      INGESTOR_QUEUE_NAME: "petrel-project-ingestion"
      POST_PROCESS_QUEUE_NAME: "petrel-storage-post-processing"
      PDS_DEFAULT_CLOUD_PLATFORM: "azure"
      AZURE_COSMOS_DATABASE_NAME: "pds"
      AZURE_KEYVAULT_NAME: "{{ .Values.azure.keyvault.name }}"
      AZURE_OSDU_KEYVAULT_NAME: "{{ .Values.azure.keyvault.name }}"
      APPINSIGHTS_ENABLE_DETAILED_TRACE: "1"
      DATA_PARTITION_REGISTRY_SERVICE_URL: "http://partition.osdu-azure/api/partition/v1"
      COMPLIANCE_SERVICE_URL: "http://legal.osdu-azure/api/legal/v1"
      ENTITLEMENT_SERVICE_URL: "http://entitlements.osdu-azure/api/entitlements/v2"
      FUNCTION_URL: "http://pds-function-service"
      DES_SERVICE_HOST: "https://{{ .Values.ingress.dns }}"
      REDIS_INSTANCE_PORT: "6380"
      APP_ENVIRONMENT_IDENTIFIER: "cloud"
      CLOUDPROVIDER: "azure"
      PORT: "8080"
      KEYVAULT_URL: "https://{{ .Values.azure.keyvault.name }}.vault.azure.net/"
      ENABLE_OSDU_SCHEMA: "true"
      EXTERNAL_AUTH_VALIDATION: "true"
      ENABLE_PTS_USER_CONTEXT: "false"
      OIDC_URL: "N/A"
      SAUTH_SERVICE_ID: "N/A"
      SAUTH_AUDIENCES: "N/A"
      SAUTH_SECRET_NAME: "N/A"
      SDP_URL: "N/A"
      DEVELOPER_PORTAL_APP_KEY: "N/A"
  # FIXME: Specific to OSDU deployment
    secrets:
      - name: AZ_AI_INSTRUMENTATION_KEY
        key: appinsight.key
