apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.global.istio.certJob.name }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - {{ include "secret.certName" . }}
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.istio.certJob.name }}-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.istio.certJob.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.istio.certJob.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.istio.certJob.name }}
  namespace: {{ .Release.Namespace }}