{{- if .Values.global.azure.podIdentityAuthEnabled }}
{{- $mstenant := .Values.global.azure.mstenant -}}
{{- $namespace := .Release.Namespace }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: header-4-add-appid-from-msft-aad-token
  namespace: {{ $namespace }}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.lua.remove-user-appid-header
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.lua.appid-from-msft-aad-token
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
            inlineCode: |
              msft_issuer = "https://sts.windows.net/{{ $mstenant }}/"
              function envoy_on_request(request_handle)
                local jwt_authn = request_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.jwt_authn")
                if jwt_authn then
                  if jwt_authn[msft_issuer] then
                    if not jwt_authn[msft_issuer]["upn"] and not jwt_authn[msft_issuer]["unique_name"] then
                        request_handle:headers():add("x-app-id", jwt_authn[msft_issuer]["aud"])
                        if jwt_authn[msft_issuer]["appid"] then
                           request_handle:headers():add("x-user-id", jwt_authn[msft_issuer]["appid"])
                        end
                    end
                  end
                end
              end
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: header-5-add-appid-from-msftonline-token
  namespace: {{ $namespace }}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.lua.remove-user-appid-header
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.lua.appid-from-msftonline-token
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
            inlineCode: |
              msft_issuer = "https://login.microsoftonline.com/{{ $mstenant }}/v2.0"
              function envoy_on_request(request_handle)
                local jwt_authn = request_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.jwt_authn")
                if jwt_authn then
                  if jwt_authn[msft_issuer] then
                    if not jwt_authn[msft_issuer]["scp"] then
                      request_handle:headers():add("x-app-id", jwt_authn[msft_issuer]["aud"])
                      if jwt_authn[msft_issuer]["appid"] then
                        request_handle:headers():add("x-user-id", jwt_authn[msft_issuer]["appid"])
                      elseif jwt_authn[msft_issuer]["azp"] then
                        request_handle:headers():add("x-user-id", jwt_authn[msft_issuer]["azp"])
                      end
                    end
                  end
                end
              end
{{- end }}