{{- $namespace := .Release.Namespace }}
{{- $serviceType := .Values.service.type }}
{{- $servicePort := .Values.service.port }}
{{- $release := .Release.Name }}
{{- range .Values.configuration }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service }}
  namespace: {{ $namespace }}
  labels:
    app: {{ .service }}
    chart: {{ .Values.image.tag }}
    release: {{ .Release.Name }}
spec:
  ports:
    - protocol: TCP
      port: {{ $servicePort }}
      targetPort: 8000
  selector:
    app: {{ .service }}

---
{{- end }}
