{{- $namespace := .Release.Namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ $namespace }}
  labels:
    app: {{ .Release.Name | quote }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        aadpodidbinding: osdu-identity
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
      - image: {{ .Values.image.repository }}/dags-data-seed:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: "dags-data-init"
        env:
        - name: OSDU_IDENTITY_ID
          value: {{ .Values.azure.identity_id }}
        - name: AZURE_DNS_NAME
          value: {{ .Values.ingress.dns }}
        - name: RESOURCE_GROUP_NAME
          value: {{ .Values.azure.resourcegroup }}
        - name: CONFIG_MAP_NAME
          value: {{ .Values.config.configmapname }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.azure.tenant_id }}
        - name: AZURE_ENABLE_MSI
          value: {{ .Values.azure.enable_msi | quote}}
