# This file contains the essential configs for the Azure Legal Tags Update Job

################################################################################
# Specify the azure environment specific values
#
azure:
  tenant: <azure_tenant>
  subscription: <azure_subscription>
  resourcegroup: <azure_resourcegroup>
  identity: <azure_identity>
  identity_id: <azure_identity_id>
  keyvault: <azure_keyvault>
  appid: <azure_appid>
  dns: <azure_dns>


image:
  repository: <azure_acr>
  tag: <version>
