{{- $list := split "," .Values.dataPartitions}}
{{- $esVersion := .Values.elasticsearch.version}}
{{- $primaryUserName := .Values.primaryUserName}}
{{- $secondaryUserName := .Values.secondaryUserName}}
{{- $userJobName := .Values.userJobName}}

{{- range $index, $datapartition := $list}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $userJobName }}"
  namespace: "es-{{ lower $datapartition }}"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: "oep-user-creator"
      
    spec:
      initContainers:
      - name: health-check
        image: docker.elastic.co/elasticsearch/elasticsearch:{{ $esVersion }}
        volumeMounts:
          - name: es-basic-auth
            mountPath: /mnt/elastic/es-basic-auth
        args:
        - /bin/sh
        - -c
        - >
          set -e;
          while [ $(curl -u elastic:$(</mnt/elastic/es-basic-auth/elastic) -sw '%{http_code}' "http://elasticsearch-es-http.es-{{ lower $datapartition }}:9200/" -o /dev/null) -ne 200 ]; do
            sleep 15;
          done
      containers:
      - name: role-and-user-creator
        image: docker.elastic.co/elasticsearch/elasticsearch:{{ $esVersion }}
        volumeMounts:
          - name: es-basic-auth
            mountPath: /mnt/elastic/es-basic-auth
          - name: es-primary-auth
            mountPath: /mnt/elastic/es-primary-auth
          - name: es-secondary-auth
            mountPath: /mnt/elastic/es-secondary-auth      
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        command: 
              - sh
              - "-c"
              - |
                /bin/bash <<'EOF'
                sleep 10
                set -e
                CUSTOM_ELASTIC_ROLE="service-role"
                ROLE_JSON="{\"metadata\":{\"type\":\"role\",\"name\":\"${CUSTOM_ELASTIC_ROLE}\"},\"cluster\":[\"all\"],\"indices\":[{\"names\":[\"*\"],\"privileges\":[\"read\",\"write\",\"create\",\"delete\",\"index\",\"monitor\",\"create_index\",\"delete_index\",\"view_index_metadata\",\"manage\"]}]}"
                PRIMARY_USER_JSON="{\"password\":\"$(</mnt/elastic/es-primary-auth/es-primary-user)\" ,\"roles\":[\"${CUSTOM_ELASTIC_ROLE}\"]}"
                SECONDARY_USER_JSON="{\"password\": \"$(</mnt/elastic/es-secondary-auth/es-secondary-user)\",\"roles\":[\"${CUSTOM_ELASTIC_ROLE}\"]}"
                curl -s -i -u elastic:$(</mnt/elastic/es-basic-auth/elastic) -XPOST "http://elasticsearch-es-http.es-{{ lower $datapartition }}:9200/_security/role/${CUSTOM_ELASTIC_ROLE}" -k -H "Content-Type: application/json" -d"${ROLE_JSON}"  | tee /dev/stderr | grep "200 OK"
                curl -s -i -u elastic:$(</mnt/elastic/es-basic-auth/elastic) -XGET "http://elasticsearch-es-http.es-{{ lower $datapartition }}:9200/_security/user/{{$primaryUserName}}" -k | tee /dev/stderr | grep "404 Not Found" && curl -s -i -u elastic:$(</mnt/elastic/es-basic-auth/elastic) -XPOST "http://elasticsearch-es-http.es-{{ lower $datapartition }}:9200/_security/user/{{$primaryUserName}}" -k -H "Content-Type: application/json" -d"${PRIMARY_USER_JSON}"  | tee /dev/stderr | grep "200 OK"
                curl -s -i -u elastic:$(</mnt/elastic/es-basic-auth/elastic) -XGET "http://elasticsearch-es-http.es-{{ lower $datapartition }}:9200/_security/user/{{$secondaryUserName}}" -k | tee /dev/stderr | grep "404 Not Found" && curl -s -i -u elastic:$(</mnt/elastic/es-basic-auth/elastic) -XPOST "http://elasticsearch-es-http.es-{{ lower $datapartition }}:9200/_security/user/{{$secondaryUserName}}" -k -H "Content-Type: application/json" -d"${SECONDARY_USER_JSON}"  | tee /dev/stderr | grep "200 OK"                
                curl -X POST "http://localhost:15000/quitquitquit" || echo 'No istio at all'
                EOF
      restartPolicy: Never
      volumes:
        - name: es-basic-auth
          secret:
            secretName: "elasticsearch-es-elastic-user"
        - name: es-primary-auth
          secret:
            secretName: "es-primary-user"
        - name: es-secondary-auth
          secret:
            secretName: "es-secondary-user"
                         
---
{{- end}}
