{{- $datapartitions := split "," .Values.global.storage.partitions }}
{{- $dphashes := split "," .Values.global.storage.partitions_hash }}
{{- $namespace := .Release.Namespace }}
{{- range $idx, $partition := $datapartitions }}
{{- if $partition }}
{{- $dphash := index $dphashes $idx }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-schema-{{ $dphash }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $.Release.Name | quote }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: {{ $.Values.global.config.backoff_limit }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        aadpodidbinding: osdu-identity
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      restartPolicy: OnFailure
      containers:
      - image: {{ $.Values.global.image.repository }}/schema-data-init:{{ $.Chart.AppVersion }}
        imagePullPolicy: Always
        name: "ds-schema-init"
        env:
        - name: OSDU_IDENTITY_ID
          value: {{ $.Values.global.azure.identity_id }}
        - name: AZURE_DNS_NAME
          value: {{ $.Values.global.ingress.dns }}
        - name: RESOURCE_GROUP_NAME
          value: {{ $.Values.global.azure.resourcegroup }}
        - name: CONFIG_MAP_NAME
          value: {{ $.Values.config.configmapname }}-{{ $dphash }}
        - name: AZURE_TENANT_ID
          value: {{ $.Values.global.azure.tenant_id }}
        - name: AZURE_AD_APP_RESOURCE_ID
          value: {{ $.Values.global.azure.resource_id }}
        - name: AZURE_CLIENT_ID
          value: {{ $.Values.global.azure.client_id }}
        - name: AZURE_CLIENT_SECRET
          value: {{ $.Values.global.azure.client_secret }}
        - name: AZURE_ENABLE_MSI
          value: {{ $.Values.global.azure.enable_msi | quote }}
        - name: PARTITIONS # comma separated list of partitions
          value: {{ $partition }}
        - name: SUBSCRIPTION
          value: {{ $.Values.global.azure.subscription }}
        - name: BACKOFF_LIMIT
          value: {{ $.Values.global.config.backoff_limit | quote }}
---
{{- end }}
{{- end }}