#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Default values for osdu-azure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  debug: false
  nodepool: services
  defaultNodepool: internal
  isAutoscalingEnabled: false

################################################################################
# Specify the azure environment specific values
#
  azure:
    tenant: <azure_tenant>
    subscription: <azure_subscription>
    resourcegroup: <azure_resourcegroup>
    identity: <azure_identity>
    identity_id: <azure_identity_id>
    keyvault: <azure_keyvault>
    appid: <azure_appid>
    podIdentityAuthEnabled: <azure_podIdentityAuthEnabled>
    includePartitionSecrets: <azure_includePartitionSecrets>
    mountRedisSecrets: <azure_mountRedisSecrets>
    common_identity_id: <azure_common_identity_id>
    common_resource_id: <azure_common_resource_id>

  ################################################################################
  # Specify the Ingress Settings
  #
  ingress:
    dns: <ingress_dns>
    issuer: letsencrypt-prod-dns
    enableKeyvaultCert: <ingress_enableKeyvaultCert>

  ################################################################################
  # Specify the resource limits
  #
  resourceLimits:
    defaultCpuRequests: "0.5"
    defaultMemoryRequests: "4Gi"
    defaultCpuLimits: "1"
    defaultMemoryLimits: "4Gi"


  ################################################################################
  # Specify the Pod Identity
  #
  identity:
    name: osdu-identity


  ################################################################################
  # Specify the Service Settings
  #
  service:
    type: ClusterIP
    port: 80


################################################################################
# Specify the OSDU Services to Load
#
configuration:

  ######################
  ##  DEFAULT SERVICE
  #
  - service: default
    repository: msosdu.azurecr.io/neilpeterson/aks-helloworld
    tag: v1
    path: /*
    pathType: ImplementationSpecific
    probe: /
    replicaCount: 1
    env:
      - name: TITLE
        value: "Azure OSDU Platform - (AKS)"
    podIdentityEnvs:
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenantid