{{- $namespace := .Release.Namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name | quote }}
  namespace: "osdu-azure"
  labels:
    app: {{ .Release.Name | quote }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        aadpodidbinding: osdu-identity
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
      - image: {{ .Values.image.repository }}/helper-services-data-seeding-agent:{{ .Values.image.tag | default .Chart.Version }}
        imagePullPolicy: Always
        name: "helper-services-data-seeding-agent"
        env:
        - name: OSDU_IDENTITY_ID
          value: {{ .Values.azure.identity_id }}
        - name: RESOURCE_GROUP_NAME
          value: {{ .Values.azure.resourcegroup }}
        - name: CONFIG_MAP_NAME
          value: {{ .Values.config.configmapname }}
        - name: VERSION
          value: {{ .Values.image.tag }}
