{{- $namespace := .Release.Namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "entitlements-data-initialization-job"
  namespace: {{ $namespace }}
  labels:
    app: "entitlements-data-initialization-job"
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        aadpodidbinding: osdu-identity
    spec:
      restartPolicy: OnFailure
      containers:
      - image: {{ .Values.image.repository }}/entitlements-data-init:{{ .Values.image.tag | default .Chart.Version }}
        imagePullPolicy: Always
        name: "entitlements-data-init"
        env:
        - name: ADMIN_ID
          value: {{ .Values.azure.appid }}
        - name: SERVICE_DOMAIN
          value: {{ .Values.service.domain }}
        - name: OSDU_HOST
          value: {{ .Values.ingress.dns }}
        - name: RESOURCE_GROUP_NAME
          value: {{ .Values.azure.resourcegroup }}
        - name: PARTITIONS # comma separated list of partitions
          value: {{ .Values.storage.partitions }}
        - name: CONFIG_MAP_NAME
          value: {{ .Values.config.configmapname }}
        - name: VERSION
          value: {{ .Values.image.tag }}