apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ig-appgw-80
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- include "postOperator.annotations" . | indent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - hosts:
      - "*"
      port:
        name: http
        number: 80
        protocol: HTTP
# Not needed as it will redirect in virtual service
#      tls:
#        httpsRedirect: true
