apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-api
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "{{ .Values.global.istio.dns_host }}"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        exact: "/"
    rewrite:
      uri: /api/partition/v1/swagger-ui.html
    route:
    - destination:
        host: partition.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/partition/v1"
    route:
    - destination:
        host: partition.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/entitlements/v1"
    route:
    - destination:
        host: entitlements-azure.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/legal/v1"
    route:
    - destination:
        host: legal.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/storage/v2"
    route:
    - destination:
        host: storage.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/indexer/v2"
    route:
    - destination:
        host: indexer-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/search/v2"
    route:
    - destination:
        host: search-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/search-extensions/v1alpha"
    route:
    - destination:
        host: search-extensions.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/delivery/v2"
    route:
    - destination:
        host: delivery.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/schema-service/v1"
    route:
    - destination:
        host: schema-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/register/v1"
    route:
    - destination:
        host: register.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/crs/catalog"
    route:
    - destination:
        host: crs-catalog-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/crs/converter"
    route:
    - destination:
        host: crs-conversion-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/unit"
    route:
    - destination:
        host: unit-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/file"
    route:
    - destination:
        host: file.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/workflow"
    route:
    - destination:
        host: workflow.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/os-wellbore-ddms"
    route:
    - destination:
        host: os-wellbore-ddms.ddms-wellbore.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/notification/v1"
    route:
    - destination:
        host: notification.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/well-planning"
    route:
    - destination:
        host: well-planning.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/entitlements/v2"
    route:
    - destination:
        host: entitlements.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/seistore-svc/api/v3"
    route:
    - destination:
        host: sdms.ddms-seismic.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/ingestion"
    route:
    - destination:
        host: ingestion-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/well-delivery"
    route:
    - destination:
        host: well-delivery.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/policy/v1"
    route:
    - destination:
        host: policy-service.{{ .Values.global.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /airflow/
    route:
    - destination:
        port:
          number: 8080
        host: airflow-web.airflow.svc.cluster.local
  - match:
    - uri:
        prefix: /airflow2/
    route:
    - destination:
        port:
          number: 8080
        host: airflow2-web.airflow.svc.cluster.local
  - match:
    - uri:
        prefix: /petrel-ds/api/v1/
    route:
    - destination:
        port:
          number: 80
        host: pds-backend.ddms-petrel.svc.cluster.local
  - match:
    - uri:
        prefix: /petrel-ds/
    route:
    - destination:
        port:
          number: 80
        host: pds-frontend.ddms-petrel.svc.cluster.local

