{{- $retryattempts := .Values.global.resiliency.retry_attempts | default 0 }}
{{- $workflowRetryattempts := .Values.global.resiliency.workflow.retry_attempts | default 0 }}
{{- $retryattemptsFileService := .Values.global.resiliency.retry_attempts_file_service | default 2 }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ig-appgw-80
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- include "postOperator.annotations" . | indent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - ig-appgw-80
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /healthz
    directResponse:
      status: 200
      body:
        string: "Azure OSDU Platform"
  # The redirect for https has to happen in the virtual service,
  # otherwise it will prevent the cert-manager http01 challenge from working
  - name: redirect
    match:
    - scheme:
        exact: http
      uri:
        # This is not a perfect regex but RE2 does not allow negations so we have to hack a it
        # Note: this pattern will redirect to HTTPS all URIs NOT starting with `/.well-` (which should be the best case since your business URIs are unlikely to start with that)
        # this to let pass requests to renew certs like `/.well-known/acme-challenge/...`
        regex: "^/(([^\\.].*)|(\\.[^w].*)|(\\.w[^e].*)|(\\.we[^l].*)|(\\.wel[^l].*)|(\\.well[^\\-].*))"
    redirect:
      scheme: https
      redirectCode: 302 # 302 to not mess with risky permanent redirections since a workaround
