apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-osdu
spec:
  hub: msosdu.azurecr.io/istio
  tag: 1.14.0
  meshConfig:
    defaultConfig:
      extraStatTags:
        - request_url_path
        - request_method
      proxyStatsMatcher:
        inclusionRegexps:
        - .*upstream_rq_retry.*osdu.*
        - .*upstream_rq_retry_success.*osdu.*
        - .*upstream_rq_retry_overflow.*osdu.*
        - .*ejections_detected_consecutive_5xx.*osdu.*
        - .*ejections_enforced_total.*osdu.*
  profile: default
  values:
    global:
      proxy:
        logLevel: info
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        loadBalancerIP: "{{ .Values.global.istio.loadBalancerIP }}"
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
            outboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
            gateway:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
  components:
   ingressGateways:
   - name: istio-ingressgateway
     enabled: true
     k8s:
      replicaCount: 2
      hpaSpec:
        minReplicas: 2
   pilot:
    k8s:
      replicaCount: 2
      hpaSpec:
        minReplicas: 2
