apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-osdu
spec:
  profile: default
  values:
    global:
      proxy:
        logLevel: info
