apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-osdu
spec:
  meshConfig:
    defaultConfig:
      extraStatTags:
        - request_url_path
        - request_method
  profile: default
  values:
    global:
      proxy:
        logLevel: debug
        privileged: true
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        loadBalancerIP: "{{ .Values.global.istio.loadBalancerIP }}"
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
            outboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
            gateway:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
  components:
   ingressGateways:
   - name: istio-ingressgateway
     enabled: true
