apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-osdu
spec:
  hub: msosdu.azurecr.io/istio
  tag: 1.8.2
  meshConfig:
    defaultConfig:
      extraStatTags:
        - request_url_path
        - request_method
  profile: default
  values:
    global:
      proxy:
        logLevel: info
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
            outboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
            gateway:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
                - name: request_duration_milliseconds
                  dimensions:
                    request_url_path: request.url_path
                    request_method: request.method
  components:
   ingressGateways:
   - name: istio-ingressgateway
     enabled: true
     k8s:
      replicaCount: 2
      hpaSpec:
        minReplicas: 2
   pilot:
    k8s:
      replicaCount: 2
      hpaSpec:
        minReplicas: 2
