# {{- $namespace := .Release.Namespace }}
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-ingress
#   namespace: {{ $namespace }}
#   annotations:
#     kubernetes.io/ingress.class: azure/application-gateway
#     appgw.ingress.kubernetes.io/request-timeout: "300"
#     appgw.ingress.kubernetes.io/connection-draining: "true"
#     appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
#     cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
#     cert-manager.io/acme-challenge-type: http01
# spec:
#   tls:
#   - hosts:
#     - {{ .Values.ingress.dns }}
#     secretName: osdu-admin-certificate
#   rules:
#     - host: {{ .Values.ingress.dns }}
#       http:
#         paths:
#         - path: /airflow/*
#           backend:
#             serviceName: airflow-web
#             servicePort: 8080
