{{- $namespace := .Release.namespace }}
apiVersion: v1
kind: Service
metadata:
  name: statsd
  namespace: {{ $namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8125
    protocol: UDP
  selector:
    app: statsd
