{{- $namespace := .Release.Namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: osdu-svc-config
  namespace: {{ $namespace }}
data:
  ENV_KEYVAULT: https://{{ .Values.global.azure.keyvault }}.vault.azure.net/
  REDIS_DB_AIRFLOW: "1"
  REDIS_DB_PARTITION: "2"
  REDIS_DB_ENTITLEMENTS: "3"
  REDIS_DB_LEGAL: "4"
  REDIS_DB_STORAGE: "5"
  REDIS_DB_INDEXER: "6"
  REDIS_DB_SEARCH: "7"
  REDIS_DB_DELIVERY: "8"
  REDIS_DB_FILE: "9"
  REDIS_DB_SDMS: "10"
  REDIS_DB_EDS: "12"
---
# Adding config map for compatibility with devops/azure/charts templates
# It can be dropped if planning to migrate to helm-charts-azure templates
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: {{ $namespace }}
data:
  airflow: "1"
  partition: "2"
  entitlements-azure: "3"
  legal: "4"
  storage: "5"
  indexer-service: "6"
  search-service: "7"
  entitlements: "8"
  seismic-dms: "9"
