{{- $namespace := .Release.Namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: osdu-svc-config
  namespace: {{ $namespace }}
data:
  ENV_KEYVAULT: https://{{ .Values.global.azure.keyvault }}.vault.azure.net/
  REDIS_DB_AIRFLOW: "1"
  REDIS_DB_PARTITION: "2"
  REDIS_DB_ENTITLEMENTS: "3"
  REDIS_DB_LEGAL: "4"
  REDIS_DB_STORAGE: "5"
  REDIS_DB_INDEXER: "6"
  REDIS_DB_SEARCH: "7"
  REDIS_DB_DELIVERY: "8"
  REDIS_DB_FILE: "9"
  REDIS_DB_SDMS: "10"
