{{- $namespace := .Release.Namespace }}
{{- $serviceName := .Values.serviceName }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $serviceName }}-authz
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $serviceName }}
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: [{{ $namespace }}]
