{{- $namespace := .Release.Namespace }}
{{- $serviceName := .Values.serviceName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: policy
  namespace: {{ $namespace }}
  name: {{ $serviceName }}-policy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
