{{- $isEnabled := .Values.keda.version_2_enabled | default false -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-log-processor
  labels:
    app: airflow-log-processor
spec:
  selector:
    matchLabels:
      app: airflow-log-processor
  template:
    metadata:
      labels:
        app: airflow-log-processor
        aadpodidbinding: "osdu-identity"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: airflow-log-processor
        image: {{ .Values.image.repository }}/airflow-function:{{ .Values.image.version.airflow_log_processor | default .Chart.AppVersion }}
        imagePullPolicy: Always
        env:
          - name: AzureFunctionsJobHost__functions__0
            value: queueTrigger
          - name: FUNCTIONS_WORKER_RUNTIME
            value: dotnet
          - name: AzureLogWorkspaceLogName
            value: airflow_dag
          - name: AzureLogWorkspaceCustomerId
            valueFrom:
              secretKeyRef:
                name: {{ .Values.logAnalytics.workspaceId.secretName }}
                key: {{ .Values.logAnalytics.workspaceId.secretKey }}
          - name: AzureLogWorkspaceSharedKey
            valueFrom:
              secretKeyRef:
                name: {{ .Values.logAnalytics.workspaceKey.secretName }}
                key: {{ .Values.logAnalytics.workspaceKey.secretKey }}
          - name: AzureWebJobsStorage
            valueFrom:
              secretKeyRef:
                name: airflow
                key: storage-connection
